name: Full CI
on: 
  push:

permissions:
  write-all
  

jobs:
  build:
    name: Build requirements image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get version
      id: version
      run: |
        git fetch --tags > /dev/null # No need to print the whole list...
        echo "setting version $(git describe --tags) as image tag" 
        echo "bec_version=$(git describe --tags)" >> $GITHUB_OUTPUT

    - name: Buildah build
      id: container-build
      uses: redhat-actions/buildah-build@v2
      with:
        image: bec_procedure_worker_requirements
        tags: ${{ steps.version.outputs.bec_version }} ${{ github.sha }}
        containerfiles: |
          ./bec_server/bec_server/scan_server/procedures/Containerfile.requirements
        build-args: |
          BEC_VERSION=${{ steps.version.outputs.bec_version }}
        extra-args: |
          -v ${{ github.workspace }}:/bec:ro
  
    - name: Push to registry
      id: container-push
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.container-build.outputs.image }}
        tags: ${{ steps.container-build.outputs.tags }}
        registry: ghcr.io/d-perl
        username: d-perl
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.container-push.outputs.registry-paths }}"