name: Full CI
on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      BEC_WIDGETS_BRANCH:
        description: 'Branch of BEC Widgets to install'
        required: false
        type: string
      BEC_CORE_BRANCH:
        description: 'Branch of BEC Core to install'
        required: false
        type: string
      OPHYD_DEVICES_BRANCH:
        description: 'Branch of Ophyd Devices to install'
        required: false
        type: string

permissions:
  write-all
  

jobs:
  build:
    name: Build requirements image
    needs: release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Buildah build
      id: container-build
      uses: redhat-actions/buildah-build@v2
      with:
        image: bec_procedure_worker_requirements
        tags: ${{ github.ref_name }} ${{ github.sha }}
        containerfiles: |
          ./bec_server/bec_server/scan_server/procedures/Containerfile.requirements
        build-args: |
          BEC_VERSION=${{ github.ref_name }}
        extra-args: |
          -v "${{ github.workspace }}:/bec:ro"
  
    - name: Push to registry
      id: container-push
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.container-build.outputs.image }}
        tags: ${{ steps.container-build.outputs.tags }}
        registry: ghcr.io/d-perl
        username: d-perl
        password: ${{ GITHUB_TOKEN }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.container-push.outputs.registry-paths }}"