name: Full CI
on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      BEC_WIDGETS_BRANCH:
        description: 'Branch of BEC Widgets to install'
        required: false
        type: string
      BEC_CORE_BRANCH:
        description: 'Branch of BEC Core to install'
        required: false
        type: string
      OPHYD_DEVICES_BRANCH:
        description: 'Branch of Ophyd Devices to install'
        required: false
        type: string

permissions:
  pull-requests: write

jobs:
  check_pr_status:
    uses: ./.github/workflows/check_pr.yml

  formatter:
    needs: check_pr_status
    if: needs.check_pr_status.outputs.branch-pr == ''
    uses: ./.github/workflows/formatter.yml

